AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  killbill-lambda

  Sample SAM Template for killbill-lambda
  
# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Runtime: nodejs16.x
    Timeout: 30
    Architectures:
        - x86_64

Parameters:
  Stage:
    Type: String
    Default: test
    AllowedValues:
      - test
      - dev
      - prod
  Region:
    Type: String
    Default: us-east-1
  CatalogTable:
    Type: String
    Default: kb-catalog

Resources:
  KillBillCall:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      Description: A Lambda function to hit Kill Bill API and push the response to SQS queue.
      CodeUri: kill-bill/
      Handler: handlers/app.lambdaHandler
      Events:
        KillBillTrigger:
          Type: SQS
          Properties:
            Queue: !GetAtt InboundQueue.Arn
            BatchSize: 1
      Policies:
        - SQSSendMessagePolicy:
            QueueName: !GetAtt OutboundQueue.QueueName
      Environment:
        Variables:
          STAGE: !Ref Stage
          OUTBOUND_QUEUE: !GetAtt OutboundQueue.Arn
          REGION: !Ref Region
    Metadata: # Manage esbuild properties
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2020"
        Sourcemap: true
        EntryPoints: 
        - handlers/app.ts
  GetCatalogPlanApi:
    Type: AWS::Serverless::Function
    Properties:
      Description: A Lambda function to get plan/product detail from Catalog DynamoDB using GET Request.
      CodeUri: kill-bill/
      Handler: handlers/get-plan.handler
      MemorySize: 128
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref CatalogTable
      Environment:
        Variables:
          CATALOGTABLE: !Ref CatalogTable
      Events:
        GetPlan:
          Type: Api
          Properties:
            Path: /catalog
            Method: get
    Metadata: # Manage esbuild properties
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2020"
        Sourcemap: true
        EntryPoints: 
        - handlers/get-plan.ts
  PostCatalogPlanApi:
    Type: AWS::Serverless::Function
    Properties:
      Description: A Lambda function to get plan/product detail from Catalog DynamoDB using GET Request.
      CodeUri: kill-bill/
      Handler: handlers/post-plan.handler
      MemorySize: 128
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref CatalogTable
      Environment:
        Variables:
          CATALOGTABLE: !Ref CatalogTable
      Events:
        GetPlan:
          Type: Api
          Properties:
            Path: /catalog
            Method: post
    Metadata: # Manage esbuild properties
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2020"
        Sourcemap: true
        EntryPoints: 
        - handlers/post-plan.ts
  InboundQueue:
    Type: AWS::SQS::Queue
  OutboundQueue:
    Type: AWS::SQS::Queue
Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  KillBillCall:
    Description: "Kill Bill Call Lambda Function ARN"
    Value: !GetAtt KillBillCall.Arn
  KillBillCallIamRole:
    Description: "Implicit IAM Role created for Kill Bill Call"
    Value: !GetAtt KillBillCallRole.Arn
  GetCatalogPlanApi:
    Description: 'API Gateway endpoint URL for Prod stage for Get Catalog Plan Function'
    Value: !Sub 'https://${GetCatalogPlanApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/catalog/'
